# mkdocs.yml
site_name: Qwery List

theme:
  name: "material"
  palette:
    - scheme: slate
      primary: pink
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: default
      primary: pink
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Home: index.md
  - classes:
      - QList: qlist.md
      - Lazy: lazy.md
      - EagerQList: eager.md

plugins:
  - mkdocstrings