# mkdocs.yml
site_name: Qwery List

theme:
  site_name: "Qwery List"
  logo: qitek.png
  favicon: qitek.png
  name: "material"
  palette:
    - scheme: slate
      primary: white
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    - scheme: default
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  repo_url: https://github.com/WitoldFracek/qlist/tree/main


nav:
  - Home: index.md
  - classes:
      - QList: qlist.md
      - Lazy: lazy.md
      - EagerQList: eager.md
  - Qitek: qitek.md

plugins:
  - mkdocstrings

extra_css:
  - navbar.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences